### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'train-cow.idx'

### ISSUE THREAD

**Issue by ShivamButale** [danhdoan/cow-detection-finetune-mxnet#1]
FileNotFoundError: [Errno 2] No such file or directory: 'train-cow.idx'

**Comment by danhdoan** [comment]
I just updated to the dataset [link](https://drive.google.com/drive/folders/15mxp_1EjmMgIHwd0hTehi9R62fFS7Nik)
You can regenerate it by `gen-data.py`

**Comment by ShivamButale** [comment]
Thanks !! It worked fluently.
